# Generated by Django 4.2.20 on 2025-05-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="terms_accepted",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
