# Generated by Django 4.2.21 on 2025-05-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.BigIntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="post_code",
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
