# Generated by Django 4.2.21 on 2025-05-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="post_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
