# Generated by Django 4.2.21 on 2025-05-28 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number, e.g. +43 664 1234567",
                        regex="^\\+?[0-9\\s\\-\\(\\)]{6,20}$",
                    )
                ],
            ),
        ),
    ]
