# Generated by Django 4.2.21 on 2025-06-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="newsletter_opt_in",
            field=models.BooleanField(default=True),
        ),
    ]
