# HTTP Redirect auf HTTPS
server {
    listen 80;
    server_name coffee-crew.at www.coffee-crew.at;

    # Leite alle HTTP-Anfragen auf HTTPS um
    return 301 https://$host$request_uri;

}

# HTTPS Server
server {
    listen 443 ssl;
    server_name coffee-crew.at www.coffee-crew.at;

    root /usr/share/nginx/html;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/coffee-crew.at/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/coffee-crew.at/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location / {
        try_files $uri /index.html;
    }

    location /media/ {
        alias /app/media/;
        access_log off;
        expires 30d;
    }

    location /api/ {
        proxy_pass http://backend:8000/api/;  # Backend API weiterleiten
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

