# Generated by Django 4.2.21 on 2025-05-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_order_payment_provider_alter_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_provider",
            field=models.CharField(
                choices=[("stripe", "Stripe"), ("paypal", "Paypal")], max_length=80
            ),
        ),
    ]
