# Generated by Django 5.2.2 on 2025-06-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0013_rename_shipping_postal_code_order_shipping_post_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_post_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
