# Generated by Django 5.2.2 on 2025-06-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_alter_order_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="price",
            new_name="price_current",
        ),
    ]
