# Generated by Django 5.2.2 on 2025-06-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_rename_price_orderitem_price_current"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_first_name",
            field=models.CharField(default="max", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_last_name",
            field=models.CharField(default="mustermann", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_country",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_post_code",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
