# Generated by Django 5.2.2 on 2025-06-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_order_shipping_first_name_order_shipping_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice_address",
            field=models.CharField(default="max", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_city",
            field=models.CharField(default="höchst", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_country",
            field=models.CharField(default="austria", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_first_name",
            field=models.CharField(default="max", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_last_name",
            field=models.CharField(default="mustermann", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_post_code",
            field=models.CharField(default="6973", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
