# Generated by Django 5.2.2 on 2025-06-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_order_invoice_address_order_invoice_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_provider",
            field=models.CharField(
                blank=True,
                choices=[("DPD", "DPD"), ("POSTAUT", "Post AT")],
                help_text="The shipping provider handling this order",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_id",
            field=models.CharField(
                blank=True,
                help_text="Tracking ID for the shipment, if available",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_url",
            field=models.URLField(
                blank=True,
                help_text="URL to track the shipment, if available",
                null=True,
            ),
        ),
    ]
