# Generated by Django 5.2.2 on 2025-06-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0021_order_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_estimate",
            field=models.DateTimeField(
                blank=True, help_text="Estimated delivery time for the order", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="last_tracking_update",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time the tracking information was updated",
                null=True,
            ),
        ),
    ]
