# Generated by Django 5.2.2 on 2025-06-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0022_order_delivery_estimate_order_last_tracking_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("pending", "Pending"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                    ("refunded", "Refunded"),
                    ("returned", "Returned"),
                    ("processing", "Processing"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
    ]
