# Generated by Django 4.2.21 on 2025-05-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_item_product'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='CartProduct',
        ),
    ]
