# Generated by Django 4.2.21 on 2025-05-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_payment_provider'),
        ('cart', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
    ]
