# Generated by Django 5.2.2 on 2025-06-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_rename_item_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="price_current",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="old_price",
            new_name="price_old",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="product",
            name="on_sale",
        ),
        migrations.AddField(
            model_name="product",
            name="price_purchase",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
