# Generated by Django 5.2.2 on 2025-06-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_rename_created_product_created_at_and_more"),
    ]

    operations = []
