# Generated by Django 5.2.2 on 2025-06-09 12:45

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_force_on_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="on_sale",
            field=models.BooleanField(default=False),
        ),
    ]
