# Generated by Django 5.2.2 on 2025-06-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_force_on_sale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="on_sale",
        ),
    ]
