# Generated by Django 5.2.2 on 2025-06-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_remove_product_on_sale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="available",
        ),
    ]
