# Generated by Django 5.2.2 on 2025-06-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
