# Generated by Django 5.2.2 on 2025-06-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_alter_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="article_nr",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
