# Generated by Django 5.2.2 on 2025-06-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_product_article_nr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="article_nr",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
