"""
Django settings for beautyshop project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!mjyz1+wxiham11_b0wq=q3qdgm*qlebo0+ll9u^lyxp%t7)7g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',  # Custom app for the beauty shop
    'cart',  # Custom app for the shopping cart
    'orders',  # Custom app for order management
    'accounts',  # Custom app for user accounts
    'payments',  # Custom app for payment processing
]

LOGIN_URL = '/accounts:login/'  # URL for login page
LOGIN_REDIRECT_URL = '/'  # Redirect to Home after login
LOGOUT_REDIRECT_URL = '/login/'  # Redirect to login page after logout

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'beautyshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Directory for templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'beautyshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# added for the custom user model
AUTH_USER_MODEL = 'accounts.CustomUser'

# automatic email verification
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Console email backend for development

EMAIL_HOST = 'mail.gmx.net'  # SMTP server for sending emails
EMAIL_PORT = 587  # Port for SMTP
EMAIL_USE_TLS = True  # Use TLS for secure email sending
EMAIL_USE_SSL = False  # Do not use SSL
   
EMAIL_HOST_USER = config('EMAIL_HOST_USER')  # emailadress saved in .env file
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # Default email address for sending emails
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')  # password saved in .env file
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # Default email address for sending emails

# Stripe for payment processing (testing)
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY')  # Stripe secret key saved in .env file
STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY')  # Stripe public key saved in .env file
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET')  # Stripe webhook secret saved in .env file

# Qogita API credentials
QOGITA_EMAIL = config('QOGITA_EMAIL')  # Qogita email saved in .env file
QOGITA_PASSWORD = config('QOGITA_PASSWORD')  # Qogita password saved in .env file

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'shop/templates/shop', 'static')]

# Static Root
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (user-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
