# Generated by Django 5.2 on 2025-05-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_cartitem_items'),
        ('shop', '0004_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Items',
        ),
    ]
