# Generated by Django 5.2 on 2025-05-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_items_item'),
        ('shop', '0005_rename_product_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
