# Generated by Django 5.2 on 2025-05-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_cartitem_items'),
        ('shop', '0005_rename_product_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
