# Generated by Django 5.2 on 2025-05-01 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_items_item'),
        ('shop', '0007_rename_categorie_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='CartItem',
        ),
    ]
