# Generated by Django 4.2.20 on 2025-05-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit Card'), ('paypal', 'PayPal'), ('invoice', 'Invoice'), ('bank_transfer', 'Bank Transfer'), ('crypto', 'Crypto'), ('klara', 'Klara')], default='', max_length=30),
        ),
    ]
