"""
Django settings for beautyshop project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-!mjyz1+wxiham11_b0wq=q3qdgm*qlebo0+ll9u^lyxp%t7)7g"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost", "1753-62-178-83-52.ngrok-free.app"]


# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",  # Django Extensions for additional features
    "corsheaders",
]

# APPEND_SLASH is set to True to ensure that URLs are properly formatted with a trailing slash.
APPEND_SLASH = True


THIRD_PARTY_APPS = [
    # "rest_framework",
    # "corsheaders",
]

LOCAL_APPS = [
    "shop",
    "cart",
    "orders",
    "accounts",
    "payments",
    "emails",
    "adminpanel",
]


INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS


LOGIN_URL = "/accounts:login/"  # URL for login page
LOGIN_REDIRECT_URL = "/"  # Redirect to Home after login
LOGOUT_REDIRECT_URL = "/login/"  # Redirect to login page after logout

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "beautyshop.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # Directory for templates
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "beautyshop.wsgi.application"

# For local dev enviroment, for REACT, to get CSRF token in Browser

SESSION_COOKIE_NAME = "sessionid"

CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SAMESITE = "Lax"

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# added for the custom user model
AUTH_USER_MODEL = "accounts.CustomUser"

# automatic email verification
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"  # Console email backend for development

EMAIL_HOST = "mail.gmx.net"  # SMTP server for sending emails
EMAIL_PORT = 587  # Port for SMTP
EMAIL_USE_TLS = True  # Use TLS for secure email sending
EMAIL_USE_SSL = False  # Do not use SSL

EMAIL_HOST_USER = config("EMAIL_HOST_USER")  # emailadress saved in .env file
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # Default email address for sending emails
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")  # password saved in .env file
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # Default email address for sending emails

# Qogita API credentials
QOGITA_EMAIL = config("QOGITA_EMAIL")  # Qogita email saved in .env file
QOGITA_PASSWORD = config("QOGITA_PASSWORD")  # Qogita password saved in .env file

# Stripe for payment processing (testing)
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY")  # Stripe secret key saved in .env file
STRIPE_PUBLIC_KEY = config("STRIPE_PUBLIC_KEY")  # Stripe public key saved in .env file
STRIPE_WEBHOOK_SECRET = config(
    "STRIPE_WEBHOOK_SECRET"
)  # Stripe webhook secret saved in .env file

# Paypal for payment processing (testing)
PAYPAL_CLIENT_ID = config("PAYPAL_CLIENT_ID")  # PayPal client ID saved in .env file
PAYPAL_CLIENT_SECRET = config(
    "PAYPAL_CLIENT_SECRET"
)  # PayPal client secret saved in .env file


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


FRONTEND_URL = "http://localhost:3000"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "shop/templates/shop", "static")]

# Static Root
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Media files (user-uploaded content)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
